export const ActionTypes = {
	SET_TOKEN: "SET_TOKEN",
	SET_USER_TYPE: "SET_USER_TYPE",
	SET_USER_AUTH: "SET_USER_AUTH",
	REMOVE_USER_AUTH: "REMOVE_USER_AUTH",

	SET_DASHBOARD: "SET_DASHBOARD"

};
